[package]
name = "jsi-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "quote"] }

[features]
host-object-trace = []
